#!/bin/bash

# bash script template with control structures, argument parsing and logging

# Log level (0 standard, 1 verbose)
log_level=0

usage() {
  echo "I am doing absolutely nothing"
  echo "Usage: $0 [-h] [-v]"
  echo "  -h      Display this message"
  echo "  -v      Be verbose" 
}

log_error() {
  echo "$@" >&2
}

log() {
  if [[ $log_level -eq 1 ]]; then
    echo "$@"
  fi
}

main()
{
  echo "Main"
  log "Log Main"
  log_error "Error Main"
}

# Parsing arguments
if [ $# -eq 1 ]; then
  if [ "$1" == "-h" ]; then
    usage
    exit 0
  elif [ "$1" == "-v" ]; then
    log_level=1
    log "Log Level set to verbose!"
  else
    log_error "Illegal Argument!"
    usage
    exit 1
  fi
elif [ $# -ge 2 ]; then
  log_error "At most one argument is permitted!" 
  usage
  exit 1
fi

# Go to main method
main

