#!/bin/bash
# script to configure my monitors, called from i3wm
xrandr_output=$(xrandr)
# Only desktop has DVI
if [[ $xrandr_output == *"DVI-D-0 connected"* ]]
then
        xrandr --output DVI-D-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
               --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal \
               --output DP-5 --off \
               --output DP-4 --off \
               --output DP-3 --off \
               --output DP-2 --off \
               --output DP-1 --off \
               --output DP-0 --off
#elif... case Laptop
# For now just assuming Laptop without external monitor
# TODO configure for 2nd monitor on HDMI if there is one
fi

