#!/bin/bash

# Kill allready running instances
killall -q polybar

# Check if on Arch -> Desktop
kernel_release=$(uname -r)
lan_interface=""

if [[ $kernel_release = *"ARCH"* ]]; then
  lan_interface="enp8s0"
else
  # Laptop interface
  lan_interface="enp2s0f1"
fi

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    POLYBAR_MONITOR=$m polybar --reload top &
    POLYBAR_MONITOR=$m LAN_INTERFACE=$lan_interface polybar --reload bottom &
  done
else
  polybar --reload top &
  polybar --reload bottom &
fi
